### ISSUE TITLE
登陆后，收藏首页的文章，然后取消收藏。在下拉刷新又会变成收藏状态

### ISSUE THREAD

**Issue by zhoujianli1016** [jsyjst/Yuan-WanAndroid#1]

**Comment by jsyjst** [comment]
Thank your issue，问题已解决。主要是图片selector问题，我忘记将未收藏的图片加上android:state_selected="false"，另外也修改了收藏接口的代码，具体修改处可以看下这个commit：https://github.com/jsyjst/Yuan-WanAndroid/commit/352bfe69305a9f2b2115f61efd60394d44390354
