### ISSUE TITLE
里面的动画很好看，可以独立出来吗，或者出一份教程

### ISSUE THREAD

**Issue by Xiosn** [jsyjst/Yuan-WanAndroid#2]
我是新手，想学习一下动画部分

**Comment by jsyjst** [comment]
Thank your issue!请问是哪部分的动画？如果是登录注册界面的话可以参考下这个开源库：https://github.com/glomadrian/Grav

**Comment by Xiosn** [comment]
谢谢，都想学习了解下哈哈，请问有启动页动画部分的domo吗

**Comment by jsyjst** [comment]
你可以参考下这个github地址：https://github.com/RomainPiel/Titanic。里面就有这个demo

**Comment by jsyjst** [comment]
你可以参考下这个github地址：https://github.com/RomainPiel/Titanic。
里面就有这个demo

**Comment by jsyjst** [comment]
你可以参考下这个github地址：https://github.com/RomainPiel/Titanic
里面就有这个demo

**Comment by hsxiaodev** [comment]
哥，不好意思啊，又要麻烦你了，请问“”关于我们“界面的纸飞机动画是怎么实现的
