### ISSUE TITLE
文章列表详情error

### ISSUE THREAD

**Issue by zht392204992** [jsyjst/Yuan-WanAndroid#3]
不错，学习一下！已star！ 首页跳转至文章详情页面，老是提示“出错啦，点击空白处刷新”！
我网络没问题，web端对应的item项，详情页面也没问题。

**Comment by xuboyu** [comment]
是不是需要修改成https？

**Comment by jsyjst** [comment]
Thank your  issue!  项目发布前已经修改了https了，不过我试过几个机型似乎没出现楼主所遇到的问题,都可以打开详细页面的，这个提示是网络有问题时才出现的。
